replace_list = [(' & ', ' and '), (' + ', ' and '), (" n' ", ' n '), (" 'n' ", ' n '), (' u ', ' you '), ('.', ''),
                ('-', ''), (',', '')]

goodbyes = [
    "See you later, alligator!",
    "After a while, crocodile.",
    "Stay out of trouble.",
    "I'm out of here.",
    "Okay...bye, fry guy!",
    "If I don't see you around, I'll see you square.",
    "Stay classy.",
    "Fare thee well.",
    "Catch you on the rebound.",
    "Gotta go, buffalo.",
    "Peace out!",
    "Gotta hit the road.",
    "Long live and prosper!",
    "Well, I'm off!",
    "Smoke me a kipper, I'll be back for breakfast.",
    "Bye bye, butterfly.",
    "Gotta get going.",
    "To the winch, wench!",
    "It has been emotional, bye.",
    "Out to the door, dinosaur.",
    "Catch you on the flip side.",
    "Gotta bolt!",
    "See you soon, racoon.",
    "You're still here? It's over. Go home. Go!",
    "Don't get run over!",
    "Have a good one.",
    "It was nice to see you again.",
    "Hasta la vista, baby.",
    "Later, haters.",
    "Give a hug, ladybug.",
    "I gotta bounce.",
    "Toodle-pip!",
    "Calc you later!",
    "See you on the other side.",
    "Take care, butterfly.",
    "Have fun storming the castle!",
    "Adieu, cockatoo!",
    "Blow a kiss, goldfish.",
    "It's been a pleasure and a privilege to meet you.",
    "Don't get attacked by a bear, it's night-time!",
    "Be good and don't get caught.",
    "Thank you for your cooperation. Farewell.",
    "I look forward to our next meeting.",
    "I'm gonna make a like a bakery truck and haul buns.",
    "Chop chop, lollipop!",
    "Gotta roll!",
    "Can't star, blue jay.",
    "Oh, and in case I don't see you - good afternoon, good evening, and good night!",
    "Influence everyone in a good way!",
    "Don't forget to come back!",
    "Once more unto the breach, dear friends!",
    "See ya, wouldn't wanna be ya.",
    "Peace out, girl scout!",
    "Adios, hippos.",
    "Time to scoot, little newt.",
    "Smell ya later!",
    "I gotta jet.",
    "Happy trails!",
    "Cheerio!",
    "Bye for now.",
    "Tootle-loo, kangaroo.",
    "Don't get lost on your way to class!",
    "Love, peace, and chicken grease.",
    "I'm off like a dirty shirt.",
    "See you when I see you.",
    "In a while, crocodile.",
    "Catch ya later, future dudes!",
    "Cya.",
    "As you wish, jellyfish!",
    "Later, skater!",
    "May the force be with you... always.",
    "Shine on, you crazy diamonds.",
    "Parting is such sweet sorrow, that I shall say good night till it be tomorrow.",
    "Don't let the door hit ya where the good lord split ya.",
    "Better shake, rattlesnake!",
    "Later, potato!",
    "Don't forget to be awesome.",
    "Later, nerds!",
    "Stay cool, my dude.",
    "Don't get cut by a blade of grass!",
    "Be sweet, parakeet.",
    "Be careful! Don't get mauled by a squirrel!",
    "See you later, aggregator!",
    "Don't trip on a raindrop!",
    "See you soon, baboon!",
    "Bye! I tolerate you!",
    "Gotta go, the power of the shower compels me.",
    "Make new friends on the sidewalk!",
    "I'm late for my bus, gigantopithecus!",
    "Move out, brussels sprout!",
    "Make sure the doormat says goodbye!",
    "I'll show you to the door!",
    "Ciao ciao, brown cow!",
    "Screw you guys, I'm going home!",
    "See you, space cowboy.",
    "I shall return.",
    "Catch you round like a rissole!",
    "Take it easy, greasy. You've got a long way to slide.",
    "Toodaloo, caribou!",
    "I'm outtie.",
    "Adios, amigos.",
    "That's all folks.",
    "Take care, polar bear!",
    "Peace out, rainbow trout!",
    "I'm outta here like spit through a trumpet.",
    "Au revoir!",
    "See you in the future.",
    "Begone!",
    "Until next time.",
    "So long, suckers!",
    "Hasta lasagna, don't get any on ya.",
    "Sayonara, muchachos!",
    "Next time, bring more cookies.",
    "Party easy, drive safe, and return with a smile on your face.",
    "After two, kangaroo!",
    "After three, chimpanzee!",
    "After four, dinosaur.",
    "Come back when you can't stay so long.",
    "Don't forget to send a letter.",
    "Goodbye forever.",
    "See you in another life, brotha!",
    "We may not talk for a long time, but I hope we don't lose touch.",
    "Never look back!",
    "See you on the internet!",
    "Forever and forever farewell. If we do meet again, we'll smile indeed. If not, 'tis true parting was well made.",
    "You will do well.",
    "See you at the restaurant at the edge of the universe!",
    "I'd say goodbye, but you're not worth it.",
    "Deuce out the roof!",
    "Hang loose, dude!",
    "kthanksbye",
    "Later, gator.",
    "See you in Hell!",
    "See you in the funny papers!",
    "Take it easy!",
    "Ta-ta!",
    "Toodles!",
    "Auf Wiedershen!",
    "Ciao!",
    "Sayonara!",
    "Adios!",
    "Merry meet, merry part, and merry meet again!",
    "Namaste",
    "Shalom",
    "I'll be back.",
    "Live long and prosper"




    ]